### DISCUSSION TITLE
Clean room button

### DISCUSSION THREAD

**Discussion by AalianKhan** [dwainscheeren/dwains-lovelace-dashboard#284] [Show and tell]
Hello!
I wanted to share a little button that I made using room addons that tells my Roborock to clean that specific room
![Screen Shot 2021-04-19 at 10 12 06 AM](https://user-images.githubusercontent.com/39784853/115250581-b50fa600-a0f7-11eb-8d29-9b8509a89c1b.png)
It's pretty useful and simple to use. 
Here is the config
In `dwains-dashboar/configs/rooms.yaml` I have this written
```YAML
rooms:
  - name: Front Hallway
    icon: mdi:coat-rack
    addons:
      - name: Clean Room
        icon: mdi:broom
        path: 'dwains-dashboard/addons/rooms/clean_room/page.yaml'
        button_path: 'dwains-dashboard/addons/rooms/clean_room/button.yaml'
        data:
          entity: vacuum.roborock_vacuum_s5
          segments: 16
```
Then I created this directory
`dwains-dashboard/addons/rooms/clean_room`
and created these files in that folder
`page.yaml`
`button.yaml`

In button.yaml I wrote
```YAML
# dwains_theme
# Custom button for room addon: hello room

type: custom:button-card
entity: {{ (data | fromjson)['entity'] }}
template: rooms_child
name: {{ name }}
icon: {{ icon|default('mdi:puzzle') }}
tap_action: 
  action: call-service
  service: xiaomi_miio.vacuum_clean_segment  
  service_data:
    entity_id: {{ (data | fromjson)['entity'] }}
    segments: {{ (data | fromjson)['segments'] }}
hold_action:
  action: more-info
  entity: {{ entity }}
label: >
  [[[ 
    if(entity){
      return entity.state;
    } else {
      return 'Entity error!';
    }
  ]]]
```
and page.YAML is just a placeholder file as it's required by Dwain-dashboard but isn't used.

To see which segments clean which room you can either just send random numbers greater than 15 like I did and test it out or 
 use the miio command-line tool, here are the [docs](https://www.home-assistant.io/integrations/xiaomi_miio/#retrieving-room-numbers).

🎉  you can now easily clean a room

**Comment by dirkpitt35** [comment]
If anyone's interested I've done the same for the Ecovacs Deebot range of robot vacuums using @AalianKhan's (thanks for the initial code!) instructions above. It's slightly different in that it uses the send_command service call. 

In dwains-dashboar/configs/rooms.yaml I have this written
```
rooms:
   - name: Entrance
     icon: hass:door-open
     addons:
      - name: Clean Room
        icon: mdi:broom
        path: 'dwains-dashboard/addons/rooms/clean_room/page.yaml'
        button_path: 'dwains-dashboard/addons/rooms/clean_room/button.yaml'
        data:
          entity: vacuum.[robot name]
          rooms: 4,5 #the room numbers correspond to the area letters in the app, so A is 0, B is 1 and so on)
```
In button.yaml I wrote
```
# dwains_theme
# Custom button for room addon: hello room

type: custom:button-card
entity: {{ (data | fromjson)['entity'] }}
template: rooms_child
name: {{ name }}
icon: {{ icon|default('mdi:puzzle') }}
tap_action: 
  action: call-service
  service: vacuum.send_command   
  service_data:
    entity_id: {{ (data | fromjson)['entity'] }}
    command: spot_area
    params:
      rooms: {{ (data | fromjson)['rooms'] }}
      cleanings: 1
hold_action:
  action: more-info
  entity: {{ entity }}
label: >
  [[[ 
    if(entity){
      return entity.state;
    } else {
      return 'Entity error!';
    }
  ]]]
```
