### DISCUSSION TITLE
help with global popups

### DISCUSSION THREAD

**Discussion by AalianKhan** [dwainscheeren/dwains-lovelace-dashboard#285] [Q&A]
Hello
I have been trying to make global popups. Everything works when I don't put variables

I want to put the entity variable so I can use it for my other lights like in the example in the docs

Here is my config for the popup.yaml
```YAML
type: entities
show_header_toggle: false
entities:
  - entity: {{ entity }}
  - type: 'custom:rgb-light-card'
    entity: {{ entity }}
    justify: around
    colors:
      - white_value: 225
        brightness: 225
        icon_color: white
      - rgb_color:
          - 234
          - 136
          - 140
        brightness: 225
      - rgb_color:
          - 251
          - 180
          - 140
        brightness: 225
      - rgb_color:
          - 135
          - 198
          - 237
        brightness: 225
      - rgb_color:
          - 139
          - 231
          - 185
        brightness: 225
      - rgb_color:
          - 249
          - 222
          - 139
        brightness: 225
```
But I get this when I reload I get this error
![Screen Shot 2021-04-19 at 4 11 46 PM](https://user-images.githubusercontent.com/39784853/115297216-f325bd80-a129-11eb-927a-c422678b3472.png)
