### ISSUE TITLE
Hold press doesn't open the more info.

### ISSUE THREAD

**Issue by flonair** [dwainscheeren/dwains-lovelace-dashboard#164]
The changelog says that you can now open the more info with a hold press. Unfortunately this does not work for me. Do I have to set it this up first? 

Because I've never seen a double tap as a gesture on a smartphone before, hold&press is much more intuitive for me.

**Comment by dwainscheeren** [comment]
You sure? It works like it needs to work over here.

**Comment by flonair** [comment]
Yes I'm sure. Hold & press don't work with my computer and not with my iphone xs.

**Comment by AalianKhan** [comment]
For me, it works for lights. media players have the 3 dots so I use that but for devices, covers and other entities it doesn't work for me.  (1.4.1)

**Comment by dwainscheeren** [comment]
I think no other people got this issue?

**Comment by flonair** [comment]
> I think no other people got this issue?

Yeah, maybe or maybe nobody else misses the feature.

Here's a video: https://imgur.com/a/5njENTI

**Comment by dwainscheeren** [comment]
Climate also doesnt have a popup so that is correct, but lights pres & hold does nothing?

**Comment by jakezp** [comment]
I have a similar thing happening. Actually depending if devices are added to a room as a single device, part of a group or under more entities, the behaviour differs...

If light is added to a room as a single device (or as part of a group):
 - single click: toggles device
 - double click: no action
 - press & hold: no action

If device is added to a room as a single device (Access from **Rooms card**):
 - single click: toggles device on or off
 - double click: toggles device on/off (quickly with each click)
 - press & hold: no action

If device is added to a room as a single device (Access from **Devices card**):
 - single click: no action
 - double click: toggles device on or off
 - press & hold: no action

If device is added to a room as part of a group:
 - single click: no action (previously - more info window would apear)
 - double click: toggles device on or off
 - press & hold: no action

If device is added under more entities:
 - single click: no action
 - double click: no action
 - press & hold: no action

Same actions would also result in different outcomes when executing from within the "Rooms" cards or the "Devices" card.
 
My blinds are added under more entities, as the built blind feature was not working for me, so now I cannot control my blinds.
My dimmabable lights cannot have brightness adjusted, since I cannot access more info at the moment.

Would be nice to have consistent clicking for single devices / grouped devices - (single click toggles, press & hold displays more info).

Thanks,
Jakez

**Comment by jakezp** [comment]
https://github.com/dwainscheeren/lovelace-dwains-theme/pull/177 <- This provides a consistent experience for lights and devices across all screens (rooms / devices views) for lights and devices. Not sure if it's done the correct way, but works for me.

single tap - toggle
double tap - more info
tap & hold - more info

**Comment by craigg204** [comment]
I am seeing the same issue, but strangely only on mobile.  On my desktop double tab and tap & hold both bring up the more info pop-up.   However on my Android device (both in the HA app and in the browser) both double tap and tap & hold cause the hapatic feedback to fire but I don't get the more info pop-up showing.

**Comment by lewisurwin** [comment]
I'm seeing the same behaviour as many above.

I have fans set up as switches in the 'more entities' section of room view and tap does nothing, where it used to toggle

**Comment by flonair** [comment]
> #177 <- This provides a consistent experience for lights and devices across all screens (rooms / devices views) for lights and devices. Not sure if it's done the correct way, but works for me.
> 
> single tap - toggle
> double tap - more info
> tap & hold - more info

I still have the same behaviour with v2.0.1. 

If I include a light as a room light ("light: light.bath") or room device ("device: light.bath"), then it behaves like this:

- single tap - toggle
- double tap - more info
- tap & hold - more info


But if I add the same light under "page_entities:", then it behaves like this:

- single tap - toggle
- double tap - **nothing**
- tap & hold - more info

That's not the way it should be, is it?

**Comment by willtho89** [comment]
It also doesn't work for me:

1. Having only a single light in my room, it works as expected (long press: more info, double press: toggle power)
2. Having a light group in my room (e.g. "Esszimmer"), only double press works; long press opens the lights view. In the view long press and double press works as expected
3. Having a light group with a mix of light groups and lights works as 2. The light groups in the lights view also work as expected (opening the more info on long press).

I have the newest release from HACS and the following config:

`rooms.yml`:
```yaml
rooms:
  - name: Esszimmer
    icon: mdi:table-chair
    light: group.esszimmer_lichter
  - name: Wohnzimmer
    icon: mdi:sofa
    light: group.wohnzimmer_lichter
```

`group.yml`:

```yaml
esszimmer_lichter:
  name: Esszimmer Licht
  icon: mdi:ceiling-light
  entities:
    - light.esszimmer_deckenlampe_oben
    - light.esszimmer_deckenlampe_unten
wohnzimmer_lightstripes:
  name: Wohnzimmer Lightstripe
  icon: mdi:led-strip-variant
  entities:
    - light.wohnzimmer_lightstripe_1
    - light.wohnzimmer_lightstripe_2
wohnzimmer_deckenlampe:
  name: Wohnzimmer Deckenlampe
  icon: mdi:ceiling-light
  entities:
    - light.wohnzimmer_deckenlampe_1
    - light.wohnzimmer_deckenlampe_2
    - light.wohnzimmer_deckenlampe_3
wohnzimmer_lichter:
  name: Wohnzimmer Lichter
  icon: mdi:lightbulb-group
  entities:
    - group.wohnzimmer_deckenlampe
    - group.wohnzimmer_lightstripes
    - light.wohnzimmer_iris
    - light.wohnzimmer_tv_lampe
    - light.wohnzimmer_stehlampe_couch
    - light.wohnzimmer_stehlampe_fenster
    - light.wohnzimmer_schrank_links
    - light.wohnzimmer_schrank_rechts
```
