### ISSUE TITLE
more_pages.yaml ==> Main_Menu option seems not working?

### ISSUE THREAD

**Issue by Flight777** [dwainscheeren/dwains-lovelace-dashboard#235]
Hi there,

I've the following configuration:

```
more_page:
    addons:
      - name: Power Usage
        main_menu: true
        icon: fas:tachometer-alt
        path: 'dwains-dashboard/addons/more_page/power_usage/power_usage.yaml'
```

Even after multiple interface refreshes, I'm not able to get the page show up in the menu bar itself (it does work under more pages button). Seems the boolean is ignored?
