### ISSUE TITLE
[FR] Add Dishwasher element in rooms

### ISSUE THREAD

**Issue by icodesdeveloper** [dwainscheeren/dwains-lovelace-dashboard#254]
Hello maybe it is interesting to add a diswasher option for the rooms. Our Siemens Dishwasher has multiple entities like remaining program time, duration, door, ... so you know that there is not one element.
Hopefully this will be added.
Regards

**Comment by AalianKhan** [comment]
I think it would wiser to use devices element for this

**Comment by joshtbernstein** [comment]
> I think it would wiser to use devices element for this

But there's not just ok/off, but other information like runtime, cycle, settings...

**Comment by dwainscheeren** [comment]
I can't make a seperate option for this, t hen I would need to extend the dashboard with hundreds of type of devices. 

1) Add your dishwasher under devices, create a custom popup for it when you click on it to control everything, state is visible on the button.
2) Create a own addon page for your dishwasher
3) Add an addon to your room and create a own dishwasher button which shows the state or anything you want on the button, links to a new dishwasher page where you can make whatever you want.
4) Same as 3 only tweak the button.yaml of the room addon and make there whatever you want for your dishwasher.

**Comment by joshtbernstein** [comment]
@dwainscheeren Those are some good alternatives. Thank you. Is there documentation for button.yaml? I wasn't able to find it.

**Comment by AalianKhan** [comment]
I think its missing from the docs but here is mine, edit it to your needs.
```YAML
# dwains_theme
# Custom button for room addon: hello room

type: custom:button-card
entity: {{ (data | fromjson)['entity'] }}
template: rooms_child
name: {{ name }}
icon: {{ icon|default('mdi:puzzle') }}
tap_action: 
  action: call-service
  service: xiaomi_miio.vacuum_clean_segment  
  service_data:
    entity_id: {{ (data | fromjson)['entity'] }}
    segments: {{ (data | fromjson)['segments'] }}
hold_action:
  action: more-info
  entity: {{ entity }}
label: >
  [[[ 
    if(entity){
      return entity.state;
    } else {
      return 'Entity error!';
    }
  ]]]
```
