### ISSUE TITLE
More Page not working

### ISSUE THREAD

**Issue by seanmccabe** [dwainscheeren/dwains-lovelace-dashboard#261]
Attempting to add a more page, and just getting the error:

_[Errno 2] No such file or directory: '/config/addons/more_page/hello-more-page/page.yaml'_

Followed the instructions from [here](https://dwainscheeren.github.io/dwains-lovelace-dashboard/addons/more_page.html).

More page config:

```
# https://dwainscheeren.github.io/dwains-lovelace-dashboard/configuration/more_page.html

more_page:
  addons:
    - name: Hello more page
      icon: mdi:chart-bar
      path: 'dwains-dashboard/addons/more_page/hello-more-page/page.yaml'
      data:
        some_data: 'This is some data parsed.'
        some_other_data: 'and some other data.'
```

/dwains-dashboard/config/addons/more_page/hello-more-page/page.yaml :

```
# dwains_theme

- type: markdown
  content: >
    This is a more page addon. It can also parse some data from the global more_page addons config.
    Don't believe it? Here it is: {{ (data | fromjson)['some_data'] }}<br>
    {{ (data | fromjson)['some_other_data'] }}
```

Will not that the sample files appear to be missing in version 2, but are still in 1.5

What am I doing wrong, appears no matter what path I put into "addons" it always pre-curors /config/addons.

**Comment by AalianKhan** [comment]
Hey, I am not having this problem. 
This is what I have in `dwains-dashboard/configs/more_page.yaml`
```yaml
# https://dwainscheeren.github.io/lovelace-dwains-theme/configuration/more_page.html

more_page:
  addons:
    - name: Hello more page
      icon: mdi:chart-bar
      path: 'dwains-dashboard/addons/more_page/hello-more-page/page.yaml'
      data:
        some_data: 'This is some data parsed.'
        some_other_data: 'and some other data.'
```
and this is what I have in `dwains-dashboard/addons/more_page/hello_more_page/page.yaml`
```
# dwains_theme

- type: markdown
  content: >
    This is a more page addon. It can also parse some data from the global more_page addons config.
    Don't believe it? Here it is: {{ (data | fromjson)['some_data'] }}<br>
    {{ (data | fromjson)['some_other_data'] }}
```

Are you sure you are not accidentally editing `dwains-dashboard/configs-samples/more_page.yaml`?
