### ISSUE TITLE
Reload UI: Unknown Error

### ISSUE THREAD

**Issue by CommittotheIndian** [dwainscheeren/dwains-lovelace-dashboard#337]
Every time I try to update rooms.yaml, I get an Unknown Error. Just to make changes, I have to restart HA, trying to reload/refresh according to the documentation, it doesn't work (nothing happens). As soon as I add the Bedroom section, I get the error. The only solution once I get the error is to completely remove the rooms.yaml and start again.

```
rooms:
  - name: Bedroom
     icon: mdi:bed-king
     vacuum:
      advanced_view: "true"
      entity: vacuum.weebette
      camera: camera.weebette_camera
  - name: Hallway
    icon: fas:key
    light: light.hallway_light
    temperature: sensor.hallway_temperature
    motion: binary_sensor.hallway_sensor_motion
    more_entities:
      entities:
        - entity: sensor.hallway_motion_battery_level
  - name: Garage
    icon: fas:garage
    door:
      entities:
        - entity: cover.travis_garage_door
        - entity: cover.katie_s_garage_door
```

Hard to diagnose anymore when it only reports an Unknown Error.

**Comment by Klumpke** [comment]
You have a typo in your code.
There is a space to much on line 3 & 4.

**Comment by CommittotheIndian** [comment]
I think that was just in copying in here. I was having issues getting the code to show up right. Forgot there's a difference in ''' and ```

Even when I removed all of the bedroom section, still get the error and have to completely remove the yaml to get it back.

Plus not showing any errors in Studio Code Server or Config Validation.

**Comment by Klumpke** [comment]
There's another error in your code.
Doors can't be covers, please see the [manual for more information](https://dwainscheeren.github.io/dwains-lovelace-dashboard/configuration/rooms.html#rooms-information).

**Comment by CommittotheIndian** [comment]
Ok again I've removed damn near everything and still get the same error.
```
rooms:
  - name: Bedroom
    icon: mdi:bed-king
    vaccum:
      advanced_view: 'true'
      entity: vacuum.weebette
      camera: camera.weebette_camera
```
