### ISSUE TITLE
Panel view or full-size view of more_page

### ISSUE THREAD

**Issue by maretodoric** [dwainscheeren/dwains-lovelace-dashboard#392]
Hello,

not sure if the naming of this thread is correct however, I'm facing "issue" when trying to use custom:floorplan-card in more_page addon. The "issue" is that it's not displayed in full size when compared to regularly opening that dashboard outside of dwains dashboard.

For example, here is the card displayed in Dwains dashboard where you can see the whole card is rather small
![image](https://user-images.githubusercontent.com/42638763/152656543-cea66158-4092-4b78-a5fe-8783241181b6.png)

This is same card displayed on default lovelace dashboard (Panel view)
![image](https://user-images.githubusercontent.com/42638763/152656579-a8a076eb-7ffb-4683-99c2-14b5a15ca218.png)

And this is on default lovelace - Masonry view
![image](https://user-images.githubusercontent.com/42638763/152656617-910ad1a0-f241-467e-8aed-c494070b4449.png)

This is a screenshot when comparing both, side-by-side
![image](https://user-images.githubusercontent.com/42638763/152834209-3522c176-bd3c-4dd8-9c89-0e2760bf1c46.png)

Sure, there's a small difference but significant because the buttons look smaller and it's harder to get clicked on.
Is there any chance that this can be somehow enlarged ?

My more_page.yaml:
```
more_page:
  addons:
    - name: Usisavanje Prizemlja
      icon: mdi:robot-vacuum
      main_menu: 'true' #Show this addon in the main navigation bar!
      path: 'dwains-dashboard/addons/more_page/vacuum-prizemlje/page.yaml'
```

And beginning of page.yaml (not to post the whole config since it's huge)
```
- type: horizontal-stack
  cards:
    - type: custom:floorplan-card
      config:
        image:
          location: /local/floorplan/prizemlje/ds-floorplan-vacuum-v2.svg
          cache: false
        stylesheet: /local/floorplan/prizemlje/floorplan.css
        full_height: true
        rules:
```

I've tried to change the type to vertical-stack and removing the type (so a single custom:floorplan-card) and there is no difference.

Great project btw, I'm loving it!

**Comment by maretodoric** [comment]
Now this is weird.... I haven't made any changes to `page.yaml` in fact, I've added same path as addon to home_information.yaml and it's displayed a lot better when looking from Home Information. When looking as a More Page now it's A LOT tinier !

For example, House Information, configuration:
```
  addons:
    - name: Grejanje
      icon: mdi:fire
      path: 'dwains-dashboard/addons/house_information/grejanje/page.yaml'
    - name: Usisavanje
      icon: mdi:robot-vacuum
      path: 'dwains-dashboard/addons/more_page/vacuum-prizemlje/page.yaml'
```
House information screenshot:
![image](https://user-images.githubusercontent.com/42638763/152834016-cd9b3663-3e28-4b2d-9614-02b0405612b7.png)

more_page configuration:
```
more_page:
  addons:
    - name: Usisavanje Prizemlja
      icon: mdi:robot-vacuum
      main_menu: 'true' #Show this addon in the main navigation bar!
      path: 'dwains-dashboard/addons/more_page/vacuum-prizemlje/page.yaml'
```

more_page screenshot:
![image](https://user-images.githubusercontent.com/42638763/152833509-d4d85f64-8b5e-4a64-acab-533f87698f8a.png)
