### ISSUE TITLE
Formatting of more_pages

### ISSUE THREAD

**Issue by der1igedon** [dwainscheeren/dwains-lovelace-dashboard#406]
Hello,

I've got an issue with formatting the more pages since the last update. They all have a smaller layout and don't fill the hole width of the screen anymore: 

![more_page_example](https://user-images.githubusercontent.com/21998742/155086802-68b20c0f-9878-4ada-91ad-0dd5e261187a.png)

The code for this page is the following:
```
- type: entities
  show_header_toggle: false
  entities:
    - entity: switch.kaffeemaschine_mqtt_status
      name: Power
    - entity: sensor.nodered_kaffeemaschine_uptime
      icon: mdi:clock
      name: Betriebszeit
    - entity: input_boolean.switch_sched_power_kaffeemaschine
      name: Zeitsteuerung

- type: conditional
  conditions:
    - entity: input_boolean.switch_sched_power_kaffeemaschine
      state: "on"
  card:
    type: entities
    entities:
      - type: 'custom:time-picker-card'
        entity: input_datetime.sched_power_kaffeemaschine
        hour_mode: 24
        layout:
          name: inside
          align_controls: right
          embedded: true

- type: custom:mini-graph-card
  entities:
    - entity: sensor.kaffeemaschine_mqtt_power
      color: green
  name: 'Energieverbrauch (aktuell)'
  align_state: left
  line_width: 2
  hours_to_show: 7
  points_per_hour: 60
  show:
    icon: false
    extrema: true
    points: false
    state: true

- type: custom:mini-graph-card
  entities:
    - entity: sensor.kaffeemaschine_mqtt_energy_consumption
  name: 'Energieverbrauch (7-Tage)'
  hours_to_show: 168
  aggregate_func: max
  group_by: date
  show:
    icon: false
    graph: bar
```

All other pages look perfectly formatted. Does anyone has an idea what causes this behaviour? Thank you!
