### ISSUE TITLE
DD 3.0 More Pages Lovelace card inconsistent behavior

### ISSUE THREAD

**Issue by diothar** [dwainscheeren/dwains-lovelace-dashboard#409]
I'm testing DD 3.0 alpha 5.

I'm testing loading custom lovelace cards to show my 4 cameras.   I added the code as a manual card in more_pages

```
cards:
  - aspect_ratio: 50%
    camera_image: camera.living_room
    camera_view: live
    entities:
      - entity: binary_sensor.living_room
      - entity: light.tv_lights
    type: picture-glance
  - aspect_ratio: 50%
    camera_image: camera.office
    camera_view: live
    entities:
      - entity: binary_sensor.office
      - entity: light.office_lights
    type: picture-glance
  - aspect_ratio: 50%
    camera_image: camera.entrance
    camera_view: live
    entities:
      - entity: binary_sensor.entrance
      - entity: light.christmas_stairway
      - entity: lock.front_door_3
    type: picture-glance
  - aspect_ratio: 50%
    camera_image: camera.aqara_kitchen
    camera_view: live
    entities:
      - entity: binary_sensor.aqara_kitchen_motion
      - entity: light.island_2
      - entity: climate.wall
    type: picture-glance
type: custom:dwains-flexbox-card

```

On my fire8 tablet, I'm seeing all 4 picture-glance cards. 

On my desktop, I will intermittently see only 1 or 2 of the cards, while the tablet still sees all of them.
It would also only sometimes show 2 of 4, but if I deleted 2, it would show the first two.  But if I changed the order, it would display the wrong ones. 

Attaching a screenshot where my 
![desktop shows 1 camera, tablet shows all 4](https://user-images.githubusercontent.com/94809600/155661154-06378391-fe29-47d1-aa27-1eb57127d89a.jpg)

![Would only show two, but it's showing the wrong two](https://user-images.githubusercontent.com/94809600/155661278-7edcb3f8-46d9-47da-931f-dd93d16aba2b.png)
