### ISSUE TITLE
Tuya Temperature Sensors not displayed on tiles per area

### ISSUE THREAD

**Issue by buhito81** [dwainscheeren/dwains-lovelace-dashboard#471]
Because in the native HA Tuya integration these don't have the `device_class: temperature` in the entity_state. Show up immediately after changing the entity manually.

![image](https://user-images.githubusercontent.com/101875447/165320637-cde4aec1-2b42-42a1-9449-f26c8b387c5e.png)

**Comment by dwainscheeren** [comment]
So its working now?

**Comment by buhito81** [comment]
That depends on your definition of what you've made on the area tiles. If it's to show the temperature, then no. If it's to show the state of a device with `device_class: temperature` then yes. Local tuya removes the device_class at the next refresh of the device, btw.

**Comment by dwainscheeren** [comment]
I think this is something you. need to ask at the maker of that integration. He doesnt follow the official ha (developer) docs/rules. For now you can template the sensor and add that to an area. Like for example:
```yaml
- platform: template
  sensors:
    netatmo_living_room_temperature:
      friendly_name: Living Room Temperature
      unit_of_measurement: "°C"
      device_class: temperature
      unique_id: netatmo_living_room_temperature
      value_template: "{{ state_attr('climate.netatmo_living_room', 'current_temperature') }}"
```
