### ISSUE TITLE
Persons addon in v3

### ISSUE THREAD

**Issue by tdonhauser** [dwainscheeren/dwains-lovelace-dashboard#628]
Hello,

how is it possible to use the persons addons from v2 in v3? I had some extra entities on a persons avatar on the main page and I can not get this working again.

In v2 it looked like this:

```
persons: 
  - name: MyName
    show_map: 'true'
    track: person.MyName
    addons:
      - name: Test addon
        icon: fas:chart-area
        path: 'dwains-dashboard/addons/persons/statistics/page.yaml'
```

Would be nice if anyone has an idea how to solve this. Thanks!
