### ISSUE TITLE
Device Type: input_number => Unknown ?

### ISSUE THREAD

**Issue by zibous** [dwainscheeren/dwains-lovelace-dashboard#692]
`input_number` is Unknown ?
`input_boolean` is working.

![Bildschirmfoto 2023-04-03 um 16 16 10](https://user-images.githubusercontent.com/30198737/229537186-7dc23397-ee2a-4643-b919-b6eef83aa192.png)

ha configuration
```yaml
heating_thermostate_set_temp_pack:
  # -------------------------
  # inputs
  # -------------------------
  input_boolean:
    thermostat_wohnzimmer1:
      name: Wohnzimmer Nord Solltemperatur
      min: 18
      max: 30
      step: 0.5
      mode: slider
      unit_of_measurement: "°C"
      icon: mdi:target

    thermostat_wohnzimmer2:
      name: Wohnzimmer Süd Solltemperatur
      min: 16
      max: 30
      step: 0.5
      mode: slider
      unit_of_measurement: "°C"
      icon: mdi:target
```

How can i fix this ?
Thanks.
