### ISSUE TITLE
ApexCharts cards not working in Dwains 3.6

### ISSUE THREAD

**Issue by Solarflor** [dwainscheeren/dwains-lovelace-dashboard#750]
Hello,
I have used the following ApexCharys cards in my dwains dashboard
```
apex_config:
  dataLabels:
    enabled: true
    style:
      fontSize: 18px
  legend:
    show: false
  plotOptions:
    pie:
      endAngle: 130
      startAngle: -130
chart_type: donut
header:
  colorize_states: true
  show: true
  show_states: true
  title: Bilancio Energia
series:
  - color: red
    entity: sensor.myenergi_hub_20007605_grid_import_today
    name: Importata
  - color: green
    entity: sensor.myenergi_hub_20007605_green_consumed_today
    name: Green Consumata
  - color: yellow
    entity: sensor.myenergi_hub_20007605_grid_export_today
    name: Esportata
type: custom:apexcharts-card
```
`
It looks ok during the creation of the card

![image](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/100423265/07a08f74-a5a6-4016-9508-4187272fc4d9)

but whne I save it ...

![image](https://github.com/dwainscheeren/dwains-lovelace-dashboard/assets/100423265/9d88527b-d337-4fc5-9206-edf9bd9049b8)

Thanks for your support
