### ISSUE TITLE
Large area for user selection and no text in DW settings

### ISSUE THREAD

**Issue by kris-tant** [dwainscheeren/dwains-lovelace-dashboard#886]
I have been a very happy DD user. But since two months, I have an issue with the user selection area, and with the Dwains Dashboard Setting pop-up window. The User Selection Area suddenly became very large, and the setting window does not show text anymore (see attached image). This (unexpected) behavior is consistent over different browsers as well as on a computer and in the mobile app. Any idea on how to resolve this? Thanks!  

![Image](https://github.com/user-attachments/assets/8084211b-7087-45c8-86e7-6a38e9d72bf9)

**Comment by SokratisKok** [comment]
Hello,
I had the same issue and i modify the css code in the `custom_components/dwains_dashboard/js/dwains-dashboard.js` file.

Search with `ctrl+F` for  `paper-tabs` css selector and replace the code snippet with the following:
```css
paper-tabs {
  height: 100%;
  padding-top: 10px !important;
  padding-right: 0.25rem !important;
  padding-bottom: 10px !important;
  padding-left: 0.25rem !important;
  display: flex;
  justify-content: space-evenly;
}
```
This is a quick fix at least for browser interface.
